# encoding: UTF-8

require 'rubocop/rake_task'
require 'foodcritic'
require 'rspec/core/rake_task'

RuboCop::RakeTask.new { |cop| cop.options = ['-D'] }
FoodCritic::Rake::LintTask.new { |critic| critic.options[:fail_tags] = 'any' }
RSpec::Core::RakeTask.new

desc 'Run Rubocop and Foodcritic style checks'
task style: [:rubocop, :foodcritic]

desc 'Run all style checks and unit tests'
task test: [:style, :spec]

task default: :test
